/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package salaryonhand;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author sangeethanan
 */
public class AddEmployer extends javax.swing.JFrame {

    /**
     * Creates new form AddEmployee
     */
    public AddEmployer() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        Intro.connect();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblName1 = new javax.swing.JLabel();
        lblNIC1 = new javax.swing.JLabel();
        lblAddress1 = new javax.swing.JLabel();
        lblPermanent1 = new javax.swing.JLabel();
        lblEmergency1 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtAddress1 = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtPermanent1 = new javax.swing.JTextArea();
        txtName1 = new javax.swing.JTextField();
        txtNIC1 = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtRemarks1 = new javax.swing.JTextArea();
        lblTelephone1 = new javax.swing.JLabel();
        txtTelephone1 = new javax.swing.JTextField();
        lblDate1 = new javax.swing.JLabel();
        txtDay1 = new javax.swing.JTextField();
        txtMonth1 = new javax.swing.JTextField();
        txtYear1 = new javax.swing.JTextField();
        lblGrade1 = new javax.swing.JLabel();
        lblPayRate1 = new javax.swing.JLabel();
        txtGrade1 = new javax.swing.JTextField();
        txtPayRate1 = new javax.swing.JTextField();
        lblRemarks1 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtEmergency2 = new javax.swing.JTextArea();
        btnOK1 = new javax.swing.JButton();
        btnReset1 = new javax.swing.JButton();
        btnCancel1 = new javax.swing.JButton();
        lblMsg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Employer", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N

        lblName1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblName1.setText("Name    :");

        lblNIC1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNIC1.setText("N.I.C No:");

        lblAddress1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAddress1.setText("Address :");

        lblPermanent1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPermanent1.setText("Permanent :");

        lblEmergency1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEmergency1.setText("In Case Of Emergency Contact :");

        txtAddress1.setColumns(20);
        txtAddress1.setRows(5);
        jScrollPane5.setViewportView(txtAddress1);

        txtPermanent1.setColumns(20);
        txtPermanent1.setRows(5);
        jScrollPane7.setViewportView(txtPermanent1);

        txtName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtNIC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNICActionPerformed(evt);
            }
        });

        txtRemarks1.setColumns(20);
        txtRemarks1.setRows(5);
        jScrollPane8.setViewportView(txtRemarks1);

        lblTelephone1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTelephone1.setText("Telephone No :");

        txtTelephone1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelephoneActionPerformed(evt);
            }
        });

        lblDate1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDate1.setText("Date Of Joint  :");

        txtDay1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDay1.setText("DAY");
        txtDay1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDayMouseClicked(evt);
            }
        });
        txtDay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDayActionPerformed(evt);
            }
        });

        txtMonth1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMonth1.setText("MONTH");
        txtMonth1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMonthMouseClicked(evt);
            }
        });
        txtMonth1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMonthActionPerformed(evt);
            }
        });

        txtYear1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtYear1.setText("YEAR");
        txtYear1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtYearMouseClicked(evt);
            }
        });
        txtYear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtYearActionPerformed(evt);
            }
        });

        lblGrade1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblGrade1.setText("Grade            :");

        lblPayRate1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPayRate1.setText("Rate Of Pay    :");

        txtGrade1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGradeActionPerformed(evt);
            }
        });

        txtPayRate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPayRateActionPerformed(evt);
            }
        });

        lblRemarks1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblRemarks1.setText("Remarks        :");

        txtEmergency2.setColumns(20);
        txtEmergency2.setRows(5);
        jScrollPane9.setViewportView(txtEmergency2);

        btnOK1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnOK1.setText("OK");
        btnOK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOK1ActionPerformed(evt);
            }
        });

        btnReset1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnReset1.setText("Reset");
        btnReset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnCancel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCancel1.setText("Cancel");
        btnCancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lblMsg.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMsg.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblRemarks1)
                        .addGap(7, 7, 7)
                        .addComponent(jScrollPane8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblDate1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDay1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMonth1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtYear1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblGrade1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGrade1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblName1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtName1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblAddress1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(lblPermanent1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblNIC1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNIC1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblEmergency1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblTelephone1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelephone1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblPayRate1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPayRate1)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnOK1)
                        .addGap(65, 65, 65)
                        .addComponent(btnReset1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancel1)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName1)
                    .addComponent(txtName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNIC1)
                    .addComponent(txtNIC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAddress1)
                    .addComponent(lblPermanent1)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmergency1)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelephone1)
                    .addComponent(txtTelephone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate1)
                    .addComponent(txtDay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMonth1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtYear1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGrade1)
                    .addComponent(txtGrade1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPayRate1)
                    .addComponent(txtPayRate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRemarks1)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOK1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnReset1)
                        .addComponent(btnCancel1))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtName1.setText("");
        txtNIC1.setText("");
        txtAddress1.setText("");
        txtPermanent1.setText("");
        txtEmergency2.setText("");
        txtTelephone1.setText("");
        txtDay1.setText("DAY");
        txtMonth1.setText("MONTH");
        txtYear1.setText("YEAR");
        txtGrade1.setText("");
        txtPayRate1.setText("");
        txtRemarks1.setText("");
        
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtPayRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPayRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPayRateActionPerformed

    private void txtGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGradeActionPerformed

    private void txtYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtYearActionPerformed

    private void txtYearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtYearMouseClicked
        // TODO add your handling code here:
        txtYear1.selectAll();
    }//GEN-LAST:event_txtYearMouseClicked

    private void txtMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMonthActionPerformed

    private void txtMonthMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMonthMouseClicked
        // TODO add your handling code here:
        txtMonth1.selectAll();
    }//GEN-LAST:event_txtMonthMouseClicked

    private void txtDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDayActionPerformed

    private void txtDayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDayMouseClicked
        // TODO add your handling code here:
        txtDay1.selectAll();
    }//GEN-LAST:event_txtDayMouseClicked

    private void txtTelephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelephoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelephoneActionPerformed

    private void txtNICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNICActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNICActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnOK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOK1ActionPerformed
        // TODO add your handling code here:
        String c_Name, name, nic, address, permanent, emergency, telephone, day, month, year, grade, payRate, remarks;
        c_Name = EditEmployer.c_Name;
        name = txtName1.getText().trim();
        nic = txtNIC1.getText().trim();
        address = txtAddress1.getText().trim();
        permanent = txtPermanent1.getText().trim();
        emergency  = txtEmergency2.getText().trim();
        telephone = txtTelephone1.getText().trim();
        day = txtDay1.getText().trim();
        month = txtMonth1.getText().trim();
        year = txtYear1.getText().trim();
        grade = txtGrade1.getText().trim();
        payRate = txtPayRate1.getText().trim();
        remarks = txtRemarks1.getText().trim();
        
        int count = 0;
        ResultSet row = null;
        String sql1 = ("SELECT COUNT(NAME) AS COUNT FROM EMPLOYEE WHERE NAME=" + "'" + name + "' AND C_NAME='"+c_Name+"'");
        try {
            Statement st1 = Intro.conn.createStatement();
            row = st1.executeQuery(sql1);
            if(row.next()){
                count = row.getInt("COUNT");
            }
        } catch (SQLException ex) {
            Logger.getLogger(CreateCompany.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(name.trim().length() == 0){
            lblMsg.setText("Enter Employer Name");   
        }else if(nic.trim().length() == 0){
            lblMsg.setText("Enter National Identity Card Number");
        }else if(count != 0){
            lblMsg.setText("Employer Already Exists");
        }else if(address.trim().length() == 0){
            lblMsg.setText("Enter Residence Address");
        }else if(permanent.trim().length() == 0){
            lblMsg.setText("Enter Permanent Address");
        }else if(emergency.trim().length() == 0){
            lblMsg.setText("Enter In Case Of Emergency Contact");
        }else if(telephone.trim().length() == 0){
            lblMsg.setText("Enter Telephone Number");
        }else if(!telephone.matches("\\d+") && !telephone.matches("\\d+\\s\\d+")){
            lblMsg.setText("Enter Valid Telephone Number");
        }else if(day.equals("DAY")){
            lblMsg.setText("Enter Day");
        }else if(!day.matches("\\d+") || Integer.parseInt(day) < 1 || Integer.parseInt(day) > 32){
            lblMsg.setText("Enter Valid Day");
        }else if(month.equals("MONTH")){
            lblMsg.setText("Enter Month");
        }else if(!month.matches("\\d+") || Integer.parseInt(month) > 12 && Integer.parseInt(month) < 1){
            lblMsg.setText("Enter Valid Month");
        }else if(Integer.parseInt(day) > 31 && (Integer.parseInt(month)%2 != 0 || Integer.parseInt(month) == 1) && Integer.parseInt(month) < 8
                || Integer.parseInt(day) > 30 && (Integer.parseInt(month)%2 == 0 || Integer.parseInt(month) != 1) && Integer.parseInt(month) < 8
                || Integer.parseInt(day) > 31 && Integer.parseInt(month)%2 == 0 && Integer.parseInt(month) > 7
                || Integer.parseInt(day) > 30 && Integer.parseInt(month)%2 != 0 && Integer.parseInt(month) > 7){
            lblMsg.setText("Enter Valid Day");
        }else if(year.equals("YEAR")){
            lblMsg.setText("Enter Year");
        }else if(!year.matches("\\d\\d\\d\\d")){
            lblMsg.setText("Enter Valid Year");
        }else if(Integer.parseInt(day) > 28 && Integer.parseInt(month) == 2 && Integer.parseInt(year)%4 != 0 
                || Integer.parseInt(day) > 29 && Integer.parseInt(month) == 2 && Integer.parseInt(year)%4 == 0
                || Integer.parseInt(day) > 28 && Integer.parseInt(month) == 2 && Integer.parseInt(year)%4 != 0){
            lblMsg.setText("Enter Valid Day");
        }else if(grade.trim().length() == 0){
            lblMsg.setText("Enter Grade");
        }else if(payRate.trim().length() == 0){
            lblMsg.setText("Enter Rate Of Pay");
        }else if(payRate.trim().length() == 0){
            lblMsg.setText("Enter Currency Not Text");
        }else if(remarks.trim().length() == 0){
            lblMsg.setText("Enter Remarks");
        }else{
            String date  = day+"/"+month+"/"+year;
            System.out.println(c_Name + "  " + name + "  " + nic + " " 
                    + address+ "  " + permanent + "  " + emergency + " " + telephone
                    + "  " + date + "  " + grade + " " + payRate + " " + remarks);
            String sql2 = ("INSERT INTO EMPLOYEE VALUES('" + c_Name + "','" + name + "','" + nic + "','" + address + "','" + permanent 
                    + "','" + emergency + "','" + telephone + "','" + date + "','" + grade + "','" + payRate + "','" + remarks+"')");
            try {
                Statement st2 = Intro.conn.createStatement();
                st2.executeQuery(sql2);
            } catch (SQLException ex) {
                Logger.getLogger(CreateCompany.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null, "Employer Successfully Added To Comapny");
            this.setVisible(false);
            try {
                Intro.conn.close();
            } catch (SQLException ex) {
                Logger.getLogger(CreateCompany.class.getName()).log(Level.SEVERE, null, ex);
            }           
        }  
    }//GEN-LAST:event_btnOK1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmployer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmployer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmployer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmployer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEmployer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCancel1;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnOK1;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnReset1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAddress1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDate1;
    private javax.swing.JLabel lblEmergency;
    private javax.swing.JLabel lblEmergency1;
    private javax.swing.JLabel lblGrade;
    private javax.swing.JLabel lblGrade1;
    private javax.swing.JLabel lblMsg;
    private javax.swing.JLabel lblNIC;
    private javax.swing.JLabel lblNIC1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblPayRate;
    private javax.swing.JLabel lblPayRate1;
    private javax.swing.JLabel lblPermanent;
    private javax.swing.JLabel lblPermanent1;
    private javax.swing.JLabel lblRemarks;
    private javax.swing.JLabel lblRemarks1;
    private javax.swing.JLabel lblTelephone;
    private javax.swing.JLabel lblTelephone1;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextArea txtAddress1;
    private javax.swing.JTextField txtDay;
    private javax.swing.JTextField txtDay1;
    private javax.swing.JTextArea txtEmergency1;
    private javax.swing.JTextArea txtEmergency2;
    private javax.swing.JTextField txtGrade;
    private javax.swing.JTextField txtGrade1;
    private javax.swing.JTextField txtMonth;
    private javax.swing.JTextField txtMonth1;
    private javax.swing.JTextField txtNIC;
    private javax.swing.JTextField txtNIC1;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtName1;
    private javax.swing.JTextField txtPayRate;
    private javax.swing.JTextField txtPayRate1;
    private javax.swing.JTextArea txtPermanent;
    private javax.swing.JTextArea txtPermanent1;
    private javax.swing.JTextArea txtRemarks;
    private javax.swing.JTextArea txtRemarks1;
    private javax.swing.JTextField txtTelephone;
    private javax.swing.JTextField txtTelephone1;
    private javax.swing.JTextField txtYear;
    private javax.swing.JTextField txtYear1;
    // End of variables declaration//GEN-END:variables
}
